name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building app
      run: |
       npm i
       npm run build
       
  deploy:
      needs: build
    
      runs-on: ubuntu-latest

      steps:
        env: # Or as an environment variable
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
      - uses: actions/checkout@v2
      - name: Deploying app
        run: |
         npm run deploy -- --token $FIREBASE_DEPLOY_TOKEN
       
   