name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building app
      run: |
       npm i
       npm run build
    - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
       
  deploy:
      needs: build
    
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Download production artifacts
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Deploying app
        env:
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
        run: |
         npm i
         npm run deploy -- --token $FIREBASE_DEPLOY_TOKEN
       
   